mg-shopping-master/project/MG-SHOPPING/MG-SHOPPING/Controllers/BillController.cs
using MG_Model.CodeHandle.Assets;
using MG_Model.EF;
using MG_SHOPPING.Models.Detail;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MG_SHOPPING.Controllers
{
    public class BillController : Controller
    {
        //
        // GET: /Bill/

        public ActionResult Index()
        {
            var model = (List<ModelCart>)Session["CART_ITEM"];
            ViewBag.Customer = (Customer)Session["CUSTOMER_BUOGHT"];
            return View(model);
        }

    }
}

mg-shopping-master/project/MG-SHOPPING/MG-SHOPPING/Controllers/MenuController.cs
using MG_Model.CodeHandle.Assets;
using MG_Model.CodeHandle.HomeModel;
using MG_Model.EF;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MG_Model.CodeHandle.MenuCategoryFolder;
using MG_Model.CodeHandle.MenuManagerFolder;

namespace MG_SHOPPING.Controllers
{
    public class MenuController : Controller
    {
        //
        // GET: /Memu/

        [ChildActionOnly]
        public ActionResult _getBanner()
        {
            var _p = new PublicComponent()._getMenu(10);
            return PartialView(_p);
        }
        [ChildActionOnly]
        public ActionResult _getBrands()
        {
            var _p = new PublicComponent()._getMenu(11);
            return PartialView(_p);
        }
        [ChildActionOnly]
        public ActionResult _getMainMenu()
        {
            var _p = new PublicComponent()._getMenu().Where(x=>x.Submenu!=null||x.CategoryMenu==1).ToList();
            return PartialView(_p);
        }
        [ChildActionOnly]
        public ActionResult _getLeftMenu()
        {
            var _p = new PublicComponent()._getMenu(1).Where(x=>x.Submenu==2).ToList();
            return PartialView(_p);
        }
        [ChildActionOnly]
        public ActionResult _getPolicy()
        {
            var _p = new PublicComponent()._getMenu(3);
            return PartialView(_p);
        }
        [ChildActionOnly]
        public ActionResult _getRecommend()
        {
            ViewBag.Recommend = new PublicComponent().getRecommend(4);
            var _p = new MenuManagerProvider().getAll().Where(x => x.Submenu == 32).ToList();
            return PartialView(_p);
        }
        [ChildActionOnly]
        public ActionResult _getAbout()
        {
            var _p = new PublicComponent()._getMenu(4);
            return PartialView(_p);
        }
        [ChildActionOnly]
        public ActionResult _getSale()
        {
            ViewBag.Sale = new Home().getListSale().ToArray();
            return PartialView();
        }
        [ChildActionOnly]
        public ActionResult _forType()
        {
            ViewBag.Type = new PublicComponent().getRecommend(8).ToArray();
            var _p = new MenuManagerProvider().getAll().Where(x => x.Submenu == 32).ToList();
            return PartialView(_p);
        }
        [ChildActionOnly]
        public ActionResult _getHot()
        {
            var p = new Home().getHot();
            return PartialView(p);
        }
        [ChildActionOnly]
        public ActionResult _detailInfor()
        {
            var p = new PublicComponent()._getMenu(8);
            return PartialView(p);
        }
        [ChildActionOnly]
        public ActionResult _getShared()
        {
            var p = new PublicComponent()._getMenu(5);
            return PartialView(p);
        }
        [ChildActionOnly]
        public ActionResult _Login()
        {
            var p = (User)Session["LOGIN_KEY"];
            return PartialView(p);
        }

    }
}

mg-shopping-master/project/MG-SHOPPING/MG-SHOPPING/Views/Bill/Index.cshtml
@{
    ViewBag.Title = "Hóa đơn";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model IList<MG_SHOPPING.Models.Detail.ModelCart>

@{Html.RenderAction("_getBanner", "Home");}
		<!--phan session của main-->
	<section>
		<div class="container">
			<div class="row">
				<div class="col-sm-3">
					<div class="left-sidebar">
						@{Html.RenderAction("_getLeftMenu", "Menu");}
						<div class="brands_products"><!--brands_products-->
							<div class="brands-name">
								<div class="menu-container">
      
									  <div class="top_nav">
										<h2 class="text-center">Hàng Hiệu</h2>
									  </div>
									 @{Html.RenderAction("_getBrands", "Menu");}
								</div>
							</div>
						</div><!--/brands_products-->
						
						
					</div>	
				</div>
				
				<div class="col-sm-9 padding-right">
					<section id="cart_items">
						<h2 class="text-center"><span>Mời bạn xem bảng hóa đơn</span></h2>
							<div class="table-responsive cart_info">
								<table class="table table-condensed">
									<thead>
										<tr class="cart_menu">
											<td class="image">Hình ảnh</td>
											<td class="description">Mô tả</td>
											<td class="price">Giá</td>
											<td class="quantity">Số lượng</td>
											<td class="total">Tổng Tiền</td>
										</tr>
									</thead>
									<tbody>
                                        @{var total=0;}
                                        @foreach (var i in Model)
                                        { 
                                            total+=i.price*i.quarity;
                                                <tr>
											    <td class="cart_product">
												    <img src="@i.image" alt="" />
											    </td>
											    <td class="cart_description">
												    <h4>@i.name</h4>
											    </td>
											    <td class="cart_price">
												    <p><span>@i.price &#8363;</span></p>
											    </td>
											    <td class="cart_quantity">
                                                    <p>@i.quarity</p>
											    </td>
											    <td class="cart_total">
												    <p class="cart_total_price"><span>@(i.price*i.quarity) &#8363;</span></p>
											    </td>
										    </tr>
                                        }
                                            <tr>
                                                <td>Tổng giá(Total):@total &#8363;</td>
                                            </tr>
									</tbody>
								</table>
                                </div>
                        <>
					</section> <!--/#cart_items-->

					<section id="do_action">
							<div class="heading">
								<h3 style="color:#A13091; font-weight:bold;">Những gì cần làm sau cùng để quá trình mua hàng được xác nhận.!!!</h3>
								<p>Vui lòng xem hóa đơn và điền thông tin để chúng tôi chuyển hàng tới bạn....</p>
							</div>
							<div class="row">
								<div class="col-sm-9">
									<div class="chose_area">
									<h2 class="text-center"><span>Thông tin khách hàng</span></h2>
                                        <h3>Họ tên:</h3><h2 class="text-center">@ViewBag.Customer.nameCustomer</h2>
                                        <h4>Giới tính:</h4><h3  class="text-center">@(ViewBag.Customer.sex?"Nam":"Nữ")</h3>
                                        <h4>Địa chỉ:</h4><h3  class="text-center">@ViewBag.Customer.adress</h3>
                                        <h4>SDT:</h4><h3  class="text-center">@ViewBag.Customer.phoneNumber</h3>
										<h4>Email:</h4><h3  class="text-center">@ViewBag.Customer.Email</h3>
									</div>
								</div>
							</div>
					</section><!--/#do_action-->
				</div>	
				</div>
			</div>
                
		</section>